### ISSUE TITLE
Устанавливать JWT_SECRET через переменные окружения в k8s

### ISSUE THREAD

**Issue by moleus** [moleus/highload-systems-itmo#234]
проверить, что во всех приложениях в *-default.yml прописан
```yaml
jwt:
  secret:
    sign: ${JWT_SECRET:0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg==}
```
и добавить этот енв из k8s секрета в values.yml для каждого сервиса
